create table if not exists public.procurement_document_drafts (
    id bigint generated by default as identity primary key,

    pr_no text not null,

    document_type text not null
        check (
            document_type in (
                'CANVASS',
                'ABSTRACT_OF_AWARD',
                'BAC_RESOLUTION'
            )
        ),

    document_data jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint procurement_document_drafts_pr_document_unique
        unique (pr_no, document_type)
);

create index if not exists
    idx_procurement_document_drafts_pr_no
on public.procurement_document_drafts(pr_no);

create index if not exists
    idx_procurement_document_drafts_type
on public.procurement_document_drafts(document_type);
